# Generated by Django 3.2.8 on 2022-04-13 23:42

from django.db import migrations, models
import vplayer.models


class Migration(migrations.Migration):

    dependencies = [
        ('vplayer', '0006_alter_mvideo_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maudio',
            name='cover',
            field=models.ImageField(upload_to='mycover', validators=[vplayer.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='mvideo',
            name='video',
            field=models.FileField(upload_to='myvideos'),
        ),
    ]
