# Generated by Django 3.2.8 on 2022-04-15 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vplayer', '0008_auto_20220415_0339'),
    ]

    operations = [
        migrations.AddField(
            model_name='maudio',
            name='ondelete',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maudio',
            name='onhide',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mvideo',
            name='ondelete',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mvideo',
            name='onhide',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
