# Generated by Django 3.2.8 on 2022-04-16 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vplayer', '0009_auto_20220416_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maudio',
            name='ondelete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='maudio',
            name='onhide',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mvideo',
            name='ondelete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mvideo',
            name='onhide',
            field=models.BooleanField(default=False),
        ),
    ]
