# Generated by Django 3.2.8 on 2022-04-18 02:06

from django.db import migrations, models
import vplayer.models


class Migration(migrations.Migration):

    dependencies = [
        ('vplayer', '0010_auto_20220416_0501'),
    ]

    operations = [
        migrations.AddField(
            model_name='maudio',
            name='like',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mvideo',
            name='cover',
            field=models.ImageField(default=1, upload_to='videoscover', validators=[vplayer.models.validate_file_extension]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mvideo',
            name='like',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
