# Generated by Django 3.2.8 on 2022-04-19 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import vplayer.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vplayer', '0011_auto_20220418_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maudio',
            name='cover',
            field=models.ImageField(default='', null=True, upload_to='mycover', validators=[vplayer.models.validate_file_extension]),
        ),
        migrations.CreateModel(
            name='Vcomment',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vplayer.vcomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vplayer.mvideo')),
            ],
        ),
    ]
